version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/" 
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "CET"
    labels:
        - "bump gradle dependencies"
    open-pull-requests-limit: 10
