version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/" 
    schedule:
      interval: "daily"
      time: "18:55"
      timezone: "CET"
    target-branch: "chore: Dependabot updates"
    labels:
        - "bump gradle dependencies"
    open-pull-requests-limit: 10
