AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CiCdDemoApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.demo.GreetingResource
      Runtime: provided
      FunctionName: !Ref ServiceName
      CodeUri: ../build/function.zip
      MemorySize: 1024
      Timeout: 60
      Role: !Ref LambdaExecutionRoleArn

Outputs:
  CiCdDemoApiArn:
    Value: !GetAtt CiCdDemoApi.Arn
