version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2

    working_directory: ~/gradle-ci-cd-demo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout

      - run:
          name: clean build
          command: gradle clean build

      - run: gradle test

#      - run:
#          name: Deploy application
#          command: sls deploy --stage pre
#  deploy:
#      executor: serverless-framework/default
#      steps:
#        - checkout
#        - aws-cli/setup
#        - serverless-framework/setup
#        - run:
#            command: serverless deploy -v
#            name: deploy
#workflows:
#  deploy:
#    jobs:
#      - deploy
