version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0 # use the AWS S3 orb in your configuration

workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  build-deploy: # Make a workflow to build and deploy your project
  jobs:
    - build
    - deploy:
        requires:
          - build # Only run deploy job once the build job has completed
        filters:
        branches:
          only: main # Only deploy when the commit is on the Main branch

jobs: # Define the build and deploy jobs
  build:
  working_directory: ~/gradle-ci-cd-demo
  deploy:
  docker: # Use the Docker executor for the deploy job
    - image: cimg/openjdk:18.0.2  # Specify the Docker image to use for the deploy job
  steps:
    # clean build
    - run: gradle clean build
    # run tests!
    - run: gradle test
    - checkout
    - aws-s3/sync:
        from: bucket
        to: 's3://ci-cd-demo'
        arguments: | # Optional arguments
        --acl public-read \
        --cache-control "max-age=86400"
        overwrite: true # default is false