#
# Native Quarkus CircleCI configuration file
#
version: 2
jobs:
  build:
    # Use "machine" instead of e.g. "docker" for better/faster results
    machine: true
    # Uses a "medium" sized machine - maybe increase this to "large" if you pay for CircleCI
    resource_class: medium
    working_directory: ~/gradle-ci-cd-demo
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      # Checkout the source code
      # ########################
      - checkout

      - run:
          name: Build (Standard)
          command: ./gradlew clean build


      - run:
          name: Build (Native)
          command: ./gradlew clean build -Dquarkus.package.type=native
          no_output_timeout: 30m
      - run:
          name: Verify (Native)
          command: ./gradlew verify
          no_output_timeout: 30m