name: Run PRs soon
on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  version:
    if: ${{ github.event.label.name == 'create-version' }}
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo ${{env.BRANCH_NAME}}
          echo ${{github.head_ref}}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{env.BRANCH_NAME}}
          fetch-depth: 0
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.2
        with:
          branch: ${{env.BRANCH_NAME}}
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "v${major}.${minor}.${patch}"
      - name: print
        run: |
          echo ${{ steps.versioning.outputs.version }}
      - name: Update version file
        run: echo ${{ steps.versioning.outputs.version }} > version
      - name: Commit version file
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@ugithub.com
          git add .
          git commit -m "${{ steps.versioning.outputs.version }} (automatically updated)"
          git push

  merge-me:
    needs: [version]
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30