name: Run Gradle Build on PRs
on:
  push:
    branches-ignore:
      - main
jobs:
  gradle:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle and clean build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: clean build jacocoTestCoverageVerification
          gradle-home-cache-cleanup: true

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage

      - name: Get the Coverage info
        run: |
            echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
            echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
