name: Run Gradle Build on PRs
jobs:
  gradle:
    if: github.ref != 'refs/heads/main' && github.event == push
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle and clean build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: clean build
          gradle-home-cache-cleanup: true