name: Release version
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Publish using Axion
        run: |
          # Fetch a full copy of the repo, as required by release plugin:
          git fetch --tags --unshallow
          # Run release:
          ./gradlew release
          # Run publish:
          ./gradlew publish