name: Release version
on:
  push:
    branches: [ 'main' ]
jobs:
  build:
    name: Clean build and package the code
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: build #-Dquarkus.package.type=native
          gradle-home-cache-cleanup: true

  release:
    needs: build
    name: Create Release
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/create-release@v1
        name: Create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.${{ github.run_number }}.0
          release_name: v0.${{ github.run_number }}.0

      - name: Semantic release 2
        id: semanticNew
        uses: go-semantic-release/action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo ${{ steps.semanticNew.outputs.version }}

      - name: Publish using Axion
        run: |
          # Fetch a full copy of the repo, as required by release plugin:
          git fetch --tags --unshallow
          # Run release:
          ./gradlew release